version: '3'

services:
  controller:
    build:
      context: .
      dockerfile: controller/Dockerfile
    networks:
      - management

  # node 1
  forwarder_1:
    build:
      context: .
      dockerfile: forwarder/Dockerfile
    environment:
      - HOSTNAME=forwarder_1
    networks:
      - management
      - link_1-3
      - link_1-4

  application_1:
    build:
      context: .
      dockerfile: application/Dockerfile
    network_mode: "service:forwarder_1"
    environment:
      - DESTINATION=application_2
      - HOSTNAME=application_1
      

  # node 2
  forwarder_2:
    build:
      context: .
      dockerfile: forwarder/Dockerfile
    environment:
      - HOSTNAME=forwarder_2
    networks:
      - management
      - link_2-7

  application_2:
    build:
      context: .
      dockerfile: application/Dockerfile
    network_mode: "service:forwarder_2"
    environment:
      - DESTINATION=application_1
      - HOSTNAME=application_2


  # node 3
  forwarder_3:
    build:
      context: .
      dockerfile: forwarder/Dockerfile
    environment:
      - HOSTNAME=forwarder_3
    networks:
      - management
      - link_1-3
      - link_3-5
      - link_3-9


  # node 4
  forwarder_4:
    build:
      context: .
      dockerfile: forwarder/Dockerfile
    environment:
      - HOSTNAME=forwarder_4
    networks:
      - management
      - link_1-4
      - link_4-5


  # node 5
  forwarder_5:
    build:
      context: .
      dockerfile: forwarder/Dockerfile
    environment:
      - HOSTNAME=forwarder_5
    networks:
      - management
      - link_3-5
      - link_4-5
      - link_5-6
      - link_5-7
      - link_5-8


  # node 6
  forwarder_6:
    build:
      context: .
      dockerfile: forwarder/Dockerfile
    environment:
      - HOSTNAME=forwarder_6
    networks:
      - management
      - link_5-6
      - link_6-7


  # node 7
  forwarder_7:
    build:
      context: .
      dockerfile: forwarder/Dockerfile
    environment:
      - HOSTNAME=forwarder_7
    networks:
      - management
      - link_2-7
      - link_5-7
      - link_6-7
      - link_7-8


  # node 8
  forwarder_8:
    build:
      context: .
      dockerfile: forwarder/Dockerfile
    environment:
      - HOSTNAME=forwarder_8
    networks:
      - management
      - link_5-8
      - link_7-8


  # node 9
  forwarder_9:
    build:
      context: .
      dockerfile: forwarder/Dockerfile
    environment:
      - HOSTNAME=forwarder_9
    networks:
      - management
      - link_3-9


  # Traffic capture
  pcap:
    image: corfr/tcpdump
    network_mode: "service:forwarder_3"
    command: -i any -w /data/capture.pcap
    volumes:
      - "./pcap:/data"

networks:
  # used for communication with the controller
  management:
  
  # networks being used as links between nodes in the topology
  link_1-3:
  link_1-4:
  link_2-7:
  link_3-5:
  link_3-9:
  link_4-5:
  link_5-6:
  link_5-7:
  link_5-8:
  link_6-7:
  link_7-8:
